"""Palettes, type scale, and the contrast maths that keeps them honest.

Every colour pairing used for text or for a UI boundary is measured against
WCAG 2.1, not eyeballed. `tests/test_theme.py` enforces the thresholds, so a
palette edit that quietly breaks legibility fails the build rather than
shipping. The ratios in the comments below are generated by `contrast_ratio`.
"""

from __future__ import annotations

from dataclasses import dataclass


def _channel(value: float) -> float:
    c = value / 255
    return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4


def relative_luminance(colour: str) -> float:
    """WCAG relative luminance of a #rrggbb colour."""
    h = colour.lstrip("#")
    r, g, b = (int(h[i : i + 2], 16) for i in (0, 2, 4))
    return 0.2126 * _channel(r) + 0.7152 * _channel(g) + 0.0722 * _channel(b)


def contrast_ratio(one: str, two: str) -> float:
    """WCAG contrast ratio between two colours, from 1.0 to 21.0."""
    a, b = relative_luminance(one), relative_luminance(two)
    lighter, darker = max(a, b), min(a, b)
    return (lighter + 0.05) / (darker + 0.05)


@dataclass(frozen=True)
class Palette:
    key: str
    label: str
    bg: str
    surface: str
    surface_alt: str
    border: str
    border_strong: str
    text: str
    text_muted: str
    accent: str
    accent_hover: str
    on_accent: str
    focus: str
    success: str
    warning: str
    error: str


DARK = Palette(
    key="dark",
    label="Charcoal",
    bg="#1B1C1E",  # neutral charcoal, not a blue-black
    surface="#232528",  # cards
    surface_alt="#2C2F33",  # inputs, list rows, hover fills
    border="#3C4045",  # quiet dividers
    border_strong="#626870",  # 3.2:1 on bg - clears the 3:1 UI-component rule
    text="#ECEDEF",  # 14.6:1 on bg (AAA) - off-white, never pure #FFF
    text_muted="#BABFC6",  # 9.2:1 on bg, 7.3:1 on surface_alt (AAA)
    accent="#2DD4BF",  # 9.2:1 on bg (AAA) - calm teal, not a flare
    accent_hover="#6EE7D8",  # 12.4:1 on bg (AAA)
    on_accent="#101214",  # 9.9:1 on accent (AAA)
    focus="#FFB454",  # 9.7:1 on bg (AAA) - warm, so it never reads as hover
    success="#6FD08C",  # 9.0:1 on bg (AAA)
    warning="#E3B341",  # 8.8:1 on bg (AAA)
    error="#FF9C9C",  # 8.2:1 on bg (AAA)
)

# Deliberately not a tasteful palette. This is the low-vision mode: yellow on
# black is the highest-legibility pairing there is, and every border is pure
# white so no edge can be missed.
MAXIMUM = Palette(
    key="maximum",
    label="Maximum contrast",
    bg="#000000",
    surface="#000000",
    surface_alt="#0D0D0D",
    border="#FFFFFF",
    border_strong="#FFFFFF",
    text="#FFFFFF",  # 21:1 - the highest possible
    text_muted="#FFFFFF",
    accent="#FFFF00",  # 19.6:1
    accent_hover="#FFFFFF",
    on_accent="#000000",
    focus="#00FFFF",
    success="#00FF7F",
    warning="#FFFF00",
    error="#FF8080",
)

PALETTES: dict[str, Palette] = {p.key: p for p in (DARK, MAXIMUM)}

# Type scale. The app can step every size up or down together (Ctrl +/-) so the
# whole interface scales for low-vision users without breaking the layout.
BASE_SIZES = {
    "display": 26,
    "title": 19,
    "body": 15,
    "small": 13,
    "mono": 13,
}
FONT_FAMILY = "Segoe UI"
MONO_FAMILY = "Cascadia Mono"

MIN_SCALE, MAX_SCALE, SCALE_STEP = 0.85, 1.6, 0.1


def sized(name: str, scale: float = 1.0) -> int:
    return max(10, round(BASE_SIZES[name] * scale))
